KIWI-2053 F2F | FE | Removing BRP option, webpages and tests
govuk-one-login/ipv-cri-f2f-front pull request #546
Opened 2024-12-06 16:43 UTC by MakiniKayiraGDS

## Proposed changes

[KIWI-2053] F2F | FE | Removing BRP option, webpages and tests

### What changed

- Removed the 4th radio button and corresponding text (BRP option).
- Deleted the page `/biometric-residence-permit-expire`.
- Deleted the page` /check-details-BRP`.
- Removed all references to BRPs in the frontend repository, including Welsh translations.
- Deleted all tests related to BRPs in the frontend repository.
- Browser tests that previously referenced BRP have been updated to mention UK Driving Licence (UK DL) instead.
- Removed the `F2F_YOTI_START_03_SCHEMA.json` schema along with any associated references in the `TestHarness.js` file.
- Deleted `F2F_CRI_VC_ISSUED_03_SCHEMA.json` 

### Why did it change

Biometric Residence Permits (BRPs) are set to expire on 31 December 2024 due to the Home Office's transition to a fully digital immigration status system. This move aligns with broader efforts to modernise immigration services and reduce reliance on physical documents.

### Issue tracking

- [KIWI-2053](https://govukverify.atlassian.net/jira/software/c/projects/KIWI/boards/567?selectedIssue=KIWI-2053)

## Evidence

<img width="936" alt="Screenshot 2024-12-06 at 15 27 28" src="https://github.com/user-attachments/assets/d0867fd1-4b9a-4c17-ab2e-ed01e20ef98e">
<img width="977" alt="Screenshot 2024-12-06 at 15 29 56" src="https://github.com/user-attachments/assets/22163ff9-b9b0-4585-aaae-af4576f54289">
<img width="1342" alt="Screenshot 2024-12-06 at 16 32 13" src="https://github.com/user-attachments/assets/b3dc4147-7b3a-4c6f-8dba-e4d4a9d784a4">
<img width="1352" alt="Screenshot 2024-12-06 at 16 36 42" src="https://github.com/user-attachments/assets/46626c2f-7627-482c-8fa0-f93942dde39a">

![image](https://github.com/user-attachments/assets/71a0299f-6c1b-44b3-8484-0515592d54d6)

[KIWI-2052]: https://govukverify.atlassian.net/browse/KIWI-2052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KIWI-2053]: https://govukverify.atlassian.net/browse/KIWI-2053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-10 16:23 UTC, GDainton reviewed
.

2024-12-10 16:24 UTC, GDainton requested changes
There's two schemas need deleting and the TestHarness.js file that references them needs the lines removed

2024-12-11 14:05 UTC, Z-Mohamoud commented
Can you delete this JSON schema please? 

test/browser/support/F2F_CRI_VC_ISSUED_03_SCHEMA.json

2024-12-11 16:17 UTC, Stelios-CB approved these changes

2024-12-11 16:50 UTC, GDainton submitted a review, later dismissed

2024-12-12 15:40 UTC, Stelios-CB approved these changes

2024-12-12 15:44 UTC, merged